services:
  ws-server:
    build:
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - 8080:8080
  react-client:
    build: 
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173
    depends_on:
      - ws-server
  
    
