services:
  stateful-ws-server:
    build:
      dockerfile: Dockerfile.stateful
      context: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules

  nginx:
    depends_on:
      - stateful-ws-server
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend-stateful:/usr/share/nginx/html/frontend-stateful  # Serve the static files
